email:
  fromEmail: qaswaweb@gmail.com
  fromName: 'People Space'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  68e7048b-3c6c-424b-9eda-2c8d0a15c348:
    name: Common
siteGroups:
  d177d70d-c1c0-4e08-ac1f-a2ae1cbfa3bf:
    name: 'People Space'
sites:
  38c9dad8-083e-4e82-8a38-50ca8a680dd2:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: 'People Space'
    primary: true
    siteGroup: d177d70d-c1c0-4e08-ac1f-a2ae1cbfa3bf
    sortOrder: 1
system:
  edition: solo
  live: true
  name: 'People Space'
  schemaVersion: 3.1.25
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
